st_details = []
name = input("enter the Student name: ")
reg_no = input("enter the Student register_no: ")
Standard = input("enter the Student class: ")
gender = input("enter the Student gender: ")
grades = input("enter the Student grades: ")
dob = input("enter the Student D.O.B: ")
st_details.append(f"Student Name: {name}")
st_details.append(f"Red_no: {reg_no}")
st_details.append(f"Class: {Standard}")
st_details.append(f"Gender: {gender}")
st_details.append(f"Grades: {grades}")
st_details.append(f"Date Of Birth: {dob}")
print(st_details)
